apiVersion: v1
kind: ResourceQuota
metadata:
  name: restrict-default
  namespace: default
spec:
  hard:
    count/configmaps: "0"
    count/cronjobs.batch: "0"
    count/daemonsets.extensions: "0"
    count/deployments.apps: "0"
    count/deployments.extensions: "0"
    count/jobs.batch: "0"
    count/persistentvolumeclaims: "0"
    count/pods: "0"
    count/replicasets.apps: "0"
    count/replicationcontrollers: "0"
    count/secrets: "0"
    count/services: "0"
    count/services.loadbalancers: "0"
    count/statefulsets.apps: "0"
---
apiVersion: v1
kind: Namespace
metadata:                                                                                                                          
  name: pf